"use strict";
let car = 'subaru';
console.log("is car == 'subaru'? I predict true.");
console.log(car == 'subaru');
console.log("is car !== 'subaru'? I predict true.");
console.log(car !== 'subaru');
console.log("is car == 'ford'? I predict true.");
console.log(car == 'ford');
console.log("is car !== 'ford'? I predict true.");
console.log(car !== 'ford');
console.log("is car == 'suzuki'? I predict true.");
console.log(car == 'suzuki');
console.log("is car !== 'suzuki'? I predict true.");
console.log(car !== 'suzuki');
console.log("is car == 'Honda'? I predict true.");
console.log(car == 'Honda');
console.log("is car !== 'Honda'? I predict true.");
console.log(car !== 'Honda');
console.log("is car == 'BMW'? I predict true.");
console.log(car == 'BMW');
console.log("is car !== 'BMW'? I predict true.");
console.log(car !== 'BMW');
